name: CD (Kustomize - manifest bump)

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  bump-manifests:
    if: ${{ github.event.workflow_run.conclusion == 'success' && vars.DEPLOY_ENABLED == 'true' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      # Get commit SHA from CI
      
      - name: Set variables
        run: |
          echo "SHA=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV

      
      # Install kubectl + kustomize
      
      - name: Setup tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

    
      # Update image in Kustomize (DEV)
      
      - name: Update dev manifests (kustomize)
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          cd k8s/dev

          kustomize edit set image backend=${DOCKER_USER}/skillpulse-backend:${SHA}
          kustomize edit set image frontend=${DOCKER_USER}/skillpulse-frontend:${SHA}

      # Commit changes
    
      - name: Commit + push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git add k8s/dev/kustomization.yaml
          git commit -m "chore: update dev images to ${SHA:0:7}"
          git push
